name: Snake!

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: Platane/snk@v3.5.0
        with:
          github_user_name: rcny
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
      - uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          build_dir: dist
          commit_message: Snake!
          target_branch: snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
